import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/Header";

const mediumFont = localFont({
  src: "./fonts/firago-latin-500-normal.ttf",
  fallback: ["sans-serif"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${mediumFont.className}  antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
